Repository apache/skywalking-cli, pull requests merged in 2019-12, with the labels that each got.

#19 Add release script
  Makefile
Labels: CI settings

#21 Set version 0.1.0
  swctl/main.go
Labels: bug

#24 Add download links for distribution packages
  README.md
Labels: documentation

#25 fix schema TraceBrief definition bug
  graphql/schema/schema.go
Labels: enhancement, feature
