Repository apache/skywalking-cli, pull requests merged in 2019-11, with the labels that each got.

#1 Add license file
  LICENSE
  NOTICE
Labels: documentation

#2 Set up GitHub Action for PR and push
  .github/workflows/go.yml
Labels: documentation

#3 Add some simple description
  README.md
Labels: documentation

#5 Create .asf.yaml
  .asf.yaml
Labels: documentation

#4 Add missing license header
  Makefile
  cmd/main.go
  cmd/service.go
  logger/log.go
  scripts/build
  swctl/service/list.go
  swctl/service/service.go
Labels: documentation

#8 Add command manual and documentations
  .github/workflows/go.yml
  README.md
Labels: documentation

#10 [Feature] Support instance list command
  README.md
  commands/flags/instance.go
  commands/instance/instance.go
  commands/instance/list.go
  graphql/client/client.go
  swctl/main.go
Labels: feature

#11 Set up license checker and style checker
  .github/workflows/go.yml
  .golangci.yml
  commands/flags/duration.go
  commands/flags/instance.go
  commands/instance/instance.go
  commands/instance/list.go
  commands/interceptor/duration.go
  commands/interceptor/duration_test.go
  commands/interceptor/interceptor.go
  commands/model/step.go
  commands/service/list.go
  commands/service/service.go
  display/display.go
  display/json/json.go
  display/table/table.go
  display/yaml/yaml.go
  graphql/client/client.go
  graphql/schema/schema.go
  logger/log.go
  swctl/main.go
  util/io.go
Labels: CI settings

#12 [Enhancement] List single service by service name
  commands/service/list.go
  graphql/client/client.go
Labels: enhancement

#13 [Enhancement] Add configure detection
  swctl/main.go
Labels: enhancement
