Repository apache/skywalking-cli, pull requests merged in 2020-07, with the labels that each got.

#40 Fix metrics graphql path
  graphql/metrics/metrics.go
Labels: bug

#41 Miss compiling commands
  README.md
Labels: documentation

#42 chore: move tools setup into Makefile to easy the setup work locally
  .github/workflows/go.yml
  Makefile
Labels: chore

#44 Add gRPC health check
  commands/common/common.go
  go.mod
  go.sum
  grpc/health.go
Labels: feature

#47 Chore: add missing license
  Makefile
  dist/LICENSE
  dist/licenses/LICENSE-packr
  go.mod
  go.sum
Labels: chore

#48 chore: add changelog for 0.3.0
  .github/workflows/go.yml
  CHANGES.md
  Makefile
  go.mod
Labels: chore
