Repository apache/skywalking-cli, pull requests merged in 2020-03, with the labels that each got.

#23 Add release guide doc
  CONTRIBUTING.md
  Makefile
  docs/How-to-release.md
  swctl/main.go
Labels: documentation

#28 Update merge buttons
  .asf.yaml
Labels: chore

#32 Remove a wrong statement in the release guide
  docs/How-to-release.md
Labels: documentation

#35 [Doc] Add changes doc for 0.2.0
  CHANGES.md
Labels: documentation

#36 Make the thermodynamic command support entity id
  README.md
  commands/metrics/thermodynamic/thermodynamic.go
Labels: enhancement

#37 Fix CHANGES.md typo
  CHANGES.md
Labels: documentation

#38 Update the release doc
  docs/How-to-release.md
Labels: documentation

#39 Add command `trace`
  .github/workflows/go.yml
  .gitignore
  .graphqlconfig
  Makefile
  README.md
  assets/assets.go
  assets/graphqls/aggregation/AllEndpointTopN.graphql
  assets/graphqls/aggregation/AllServiceInstanceTopN.graphql
  assets/graphqls/aggregation/EndpointTopN.graphql
  assets/graphqls/aggregation/ServiceInstanceTopN.graphql
  assets/graphqls/aggregation/ServiceTopN.graphql
  assets/graphqls/metadata/AllServices.graphql
  assets/graphqls/metadata/Instances.graphql
  assets/graphqls/metadata/SearchEndpoints.graphql
  assets/graphqls/metadata/SearchService.graphql
  assets/graphqls/metadata/ServerTimeInfo.graphql
  assets/graphqls/metrics/IntValues.graphql
  assets/graphqls/metrics/LinearIntValues.graphql
  assets/graphqls/metrics/MultipleLinearIntValues.graphql
  assets/graphqls/metrics/Thermodynamic.graphql
  assets/graphqls/trace/Trace.graphql
  cmd/main.go
  commands/trace/list.go
  commands/trace/trace.go
  display/graph/graph.go
  display/graph/tree/adapter.go
  display/graph/tree/tree.go
  dist/LICENSE
  go.mod
  go.sum
  graphql/aggregation/aggregation.go
  graphql/metadata/metadata.go
  graphql/metrics/metrics.go
  graphql/trace/trace.go
  util/lang.go
Labels: feature
