Repository apache/skywalking-cli, pull requests merged in 2020-08, with the labels that each got.

#50 Integrate global metrics and global response latency into `dashboard global` command
  assets/templates/Dashboard.Global.json
  display/graph/dashboard/global.go
  display/graph/gauge/gauge.go
  display/graph/graph.go
  display/graph/linear/linear.go
  example/Dashboard.Global.json
  graphql/dashboard/global.go
Labels: feature

#51 Fix a bug and make several improvements
  assets/templates/Dashboard.Global.json
  display/graph/dashboard/global.go
  display/graph/linear/linear.go
  example/Dashboard.Global.json
  graphql/dashboard/global.go
Labels: bug, feature

#53 Fix copy/paste issue of the health check doc
  README.md
Labels: documentation

#55 Integrated the heat map into the `dashboard global` command
  README.md
  display/graph/dashboard/global.go
  display/graph/gauge/gauge.go
  go.mod
  go.sum
  graphql/utils/adapter.go
  lib/heatmap/axes/axes.go
  lib/heatmap/axes/label.go
  lib/heatmap/heatmap.go
  lib/heatmap/options.go
Labels: feature

#57 Center the heat map
  display/graph/dashboard/global.go
Labels: enhancement

#58 Fix `dashboard global` doc
  README.md
Labels: documentation

#59 Refactor `metrics thermodynamic` command
  README.md
  assets/graphqls/metrics/Thermodynamic.graphql
  commands/metrics/thermodynamic/thermodynamic.go
  commands/model/scope.go
  display/graph/graph.go
  display/graph/heatmap/heatmap.go
  graphql/metrics/metrics.go
  lib/heatmap.go
Labels: enhancement, feature

#60 update traces search
  display/graph/tree/list.go
  display/graph/tree/tree.go
Labels: enhancement, feature
