Repository apache/skywalking-cli, pull requests merged in 2021-09, with the labels that each got.

#113 Add the sub-command 'service' of command 'dependency'
  README.md
  assets/assets.gen.go
  assets/graphqls/dependency/ServiceTopology.graphql
  internal/commands/dependency/dependency.go
  internal/commands/dependency/service.go
  pkg/graphql/dependency/dependency.go
  scripts/test_commands.sh
Labels: feature

#114 Update changelog for 0.8.0
  CHANGES.md
Labels: chore

#115 Remove `dist` directory when build release source tar
  Makefile
Labels: chore

#116 Publish Docker snapshot images to ghcr
  .github/workflows/publish-docker.yaml
  Dockerfile
  Makefile
  README.md
  docs/How-to-release.md
Labels: chore

#117 Add the sub-command 'instance' of command 'dependency'
  README.md
  assets/assets.gen.go
  assets/graphqls/dependency/InstanceTopology.graphql
  internal/commands/dependency/dependency.go
  internal/commands/dependency/instance.go
  pkg/graphql/dependency/dependency.go
  scripts/test_commands.sh
Labels: feature

#118 Fix the wrong name when getting `destInstance` flag
  internal/commands/interceptor/entity.go
Labels: bug
