Repository apache/skywalking-cli, pull requests merged in 2021-08, with the labels that each got.

#104 Profile command support
  README.md
  assets/assets.gen.go
  assets/graphqls/profile/CreateTask.graphql
  assets/graphqls/profile/GetProfileAnalyze.graphql
  assets/graphqls/profile/GetProfiledSegment.graphql
  assets/graphqls/profile/GetTaskList.graphql
  assets/graphqls/profile/GetTaskSegmentList.graphql
  cmd/swctl/main.go
  internal/commands/profile/create.go
  internal/commands/profile/getProfileAnalyze.go
  internal/commands/profile/getProfiledSegment.go
  internal/commands/profile/getTaskList.go
  internal/commands/profile/getTaskSegmentList.go
  internal/commands/profile/profile.go
  pkg/graphql/profile/profile.go
Labels: feature

#106 Add scripts for quick install
  README.md
  scripts/install.bat
  scripts/install.sh
Labels: enhancement

#107 Add a command dependency and its first sub-command endpoint
  README.md
  assets/assets.gen.go
  assets/graphqls/dependency/EndpointDependency.graphql
  cmd/swctl/main.go
  internal/commands/dependency/dependency.go
  internal/commands/dependency/endpoint.go
  pkg/graphql/dependency/dependency.go
Labels: feature

#108 Support auto-completion for bash and powershell
  README.md
  cmd/swctl/main.go
  internal/commands/completion/bash.go
  internal/commands/completion/completion.go
  internal/commands/completion/powershell.go
Labels: enhancement, feature

#110 Sync the removal of fileds in query protocol
  go.mod
  go.sum
  internal/commands/trace/list.go
Labels: chore

#111 Cancel the color text effect of swctl in windows
  cmd/swctl/main.go
Labels: bug
