Repository apache/skywalking-cli, pull requests merged in 2021-06, with the labels that each got.

#95 Upgrade dependency crypto
  dist/LICENSE
  go.mod
  go.sum
Labels: chore

#96 Add GitHub Action for integration of event reporter
  .github/scripts/entrypoint.sh
  .github/scripts/post-entrypoint.sh
  Dockerfile
  Makefile
  README.md
  action.yaml
  scripts/test_commands.sh
Labels: feature

#97 chore: update changelog for 0.7.0
  CHANGES.md
Labels: chore

#98 Chore: update release doc and add scripts for release
  docs/How-to-release.md
  scripts/pre-release.sh
  scripts/release.sh
Labels: chore, documentation
