Repository apache/skywalking-cli, pull requests merged in 2021-01, with the labels that each got.

#85 Update year to 2021
  NOTICE
  dist/NOTICE
Labels: chore

#86 chore: add changelog for 0.6.0
  CHANGES.md
Labels: chore, documentation

#83 chore: use license-eye to check license header
  .github/workflows/go.yml
  .licenserc.yaml
Labels: CI settings, chore
