Repository apache/skywalking-cli, pull requests merged in 2021-07, with the labels that each got.

#99 Optimize output by adding color to help information
  cmd/swctl/main.go
  pkg/util/template.go
Labels: enhancement

#100 Fix missing service instance name in trace command
  assets/assets.gen.go
  assets/graphqls/trace/Trace.graphql
Labels: bug

#102 set display style explicitly for commands in the test script
  scripts/test_commands.sh
Labels: CI settings, chore

#101 Set different default display style for different commands
  cmd/swctl/main.go
  pkg/display/display.go
  pkg/util/commandNotFound.go
  pkg/util/commandNotFound_test.go
Labels: enhancement

#103 Logs command support
  README.md
  assets/assets.gen.go
  assets/graphqls/logs/Logs.graphql
  cmd/swctl/main.go
  internal/commands/logs/list.go
  internal/commands/logs/log.go
  pkg/graphql/log/log.go
Labels: feature
