Repository apache/skywalking-cli, pull requests merged in 2021-02, with the labels that each got.

#89 change all flags of `event report` to non-required
  README.md
  internal/commands/event/report.go
Labels: enhancement

#87 Add missing license of swck
  dist/LICENSE
  go.mod
  go.sum
  internal/commands/install/manifest/manifest.go
Labels: chore

#90 chore: update changelog for 0.6.0
  CHANGES.md
Labels: chore, documentation

#91 Update release doc
  docs/How-to-release.md
Labels: chore, documentation
