Repository apache/skywalking-cli, pull requests merged in 2022-04, with the labels that each got.

#139 Update CHANGES.md for 0.10.0
  CHANGES.md
Labels: documentation

#140 Add `.github/scripts` to release source tarball
  Makefile
Labels: chore

#143 feature: update install.sh version regex
  scripts/install.sh
Labels: bug

#144 Update the commands relate to the process
  CHANGES.md
  assets/graphqls/metadata/v2/EstimateProcessScale.graphql
  assets/graphqls/metadata/v2/Processes.graphql
  internal/commands/process/estimate/scale.go
  internal/commands/process/list.go
  pkg/graphql/metadata/metadata.go
Labels: enhancement

#145 Add layer to event related commands
  .github/scripts/post-entrypoint.sh
  README.md
  action.yaml
  cmd/swctl/main.go
  go.mod
  go.sum
  internal/commands/event/list.go
  internal/commands/event/report.go
  pkg/commands/event/report.go
  pkg/grpc/grpc.go
Labels: enhancement

#146 Add layer to events.graphql
  assets/graphqls/event/events.graphql
Labels: enhancement

#147 Add layer field to alarms.graphql
  assets/graphqls/alarm/alarms.graphql
Labels: enhancement

#148 Upgrade crypto lib to fix cve
  .gitignore
  go.mod
  go.sum
Labels: chore
